### PR TITLE
Support FoundryVTT v9 API

### PR DESCRIPTION
**Pull request by pchouzenoux**
Changes are only to support FoundryVTT v9 API.

### CODE REVIEW

**Review by gendokun — APPROVED** [review]
Looks good

**Comment by crnormand** [comment]
You need to add:

```
    static stopAllAnimationGM() {
        MarkerAnimation.stopAllAnimation()
        game.socket.emit(socketName, {
            stopAllAnimation: 'all'
        });
    }
```

**Review by crnormand — APPROVED** [review]
I will approve, to get those changes through... but could you also add:

```
    static stopAllAnimationGM() {
        MarkerAnimation.stopAllAnimation()
        game.socket.emit(socketName, {
            stopAllAnimation: 'all'
        });
    }
```

**Comment by pchouzenoux** [comment]
> I will approve, to get those changes through... but could you also add:
> 
> ```
>     static stopAllAnimationGM() {
>         MarkerAnimation.stopAllAnimation()
>         game.socket.emit(socketName, {
>             stopAllAnimation: 'all'
>         });
>     }
> ```

Done ! I made the change

**Review by kckaiwei — APPROVED** [review]

**Pull request merged**
