### PR TITLE
[BUG] Fix start marker visibility regression

### LINKED ISSUE #24: [BUG] Start marker visibility issues
Start marker is still showing visible even when the controlled token cannot see the unit starting.

Reproduced by controlling a PC (in a client browser), then switching turns to a NPC in GM browser, and a start marker will be seen.

image

### PR DESCRIPTION
**Pull request by dev7355608**
It was working in #20, but it broke when #22 was merged.

### CODE REVIEW

**Review by kckaiwei — COMMENTED** [review]
I'm not actually seeing this work. I've made sure to pull from your fix-24 a few times. 

Currently, I'm not even seeing a startMarker get created now. 

I was messing with it earlier, and had the problem where startMarker was still shown, but setting `tile.renderable` to false, didn't actually hide it :\.

**Comment by kckaiwei** [comment]
A follow up, I'm suspecting something to do with this line:
https://github.com/kckaiwei/TurnMarker-alt/blob/47bbada6a4744bc40058e32d2fe43cf4ffd78f4f/src/scripts/turnmarker.js#L60

Since we're just deleting it again right after creating it, it seems. I'll take a deeper look after work later today.

**Comment by dev7355608** [comment]
Yes, you're right, these are in fact two issues: the merge conflict was not properly resolved, and the incorrect code before the await PR worked for some reason despite the errors in the code that should delete the start marker every time. This line is also an issue:

https://github.com/kckaiwei/TurnMarker-alt/blob/47bbada6a4744bc40058e32d2fe43cf4ffd78f4f/src/scripts/marker.js#L18

This commit should fix that.

**Comment by kckaiwei** [comment]
Yeah, I think I must've blundered the merge conflict resolution. Was multi-tasking a call while doing that, so that's on me.

Looks good to me, and I tested it out on my machine, works like a charm :)

**Review by kckaiwei — APPROVED** [review]

**Pull request merged**
